name: mlops-churn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.0.3
  - scikit-learn=1.2.2
  - xgboost=1.7.6
  - fastapi=0.95.2
  - uvicorn=0.22.0
  - joblib=1.2.0
  - evidently=0.2.4
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyterlab
  - notebook
  - pytest=7.4.2
  - pip
  - pip:
      - prometheus-fastapi-instrumentator==5.9.1
      - alibi-detect==0.11.1
